# Generated by Django 5.2.4 on 2025-07-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('remarks', models.TextField(default='')),
                ('rating', models.TextField(max_length=5)),
                ('date', models.DateField(default='timezone.now')),
            ],
        ),
    ]
