# Generated by Django 5.2.4 on 2025-07-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0003_registrations_alter_contact_date_alter_feedback_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrations',
            new_name='User',
        ),
    ]
