# Generated by Django 5.2.4 on 2025-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0004_rename_registrations_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('sport_pic', models.FileField(default='', upload_to='sport_pic/')),
            ],
        ),
    ]
