# Generated by Django 5.2.4 on 2025-08-04 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0005_sportcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13)),
                ('age', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('sport_name', models.CharField(max_length=50)),
                ('profile_pic', models.FileField(default='', upload_to='coach_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
