# Generated by Django 5.2.4 on 2025-08-06 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0006_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('course_name', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=60, primary_key=True, serialize=False)),
                ('full_name', models.EmailField(max_length=60)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('address', models.TextField(default='')),
                ('admission_status', models.CharField(default='pending', max_length=10)),
                ('pic_name', models.FileField(upload_to='admission_pic/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
