# Generated by Django 5.2.4 on 2025-08-13 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0007_admissionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
