# Generated by Django 5.2.4 on 2025-08-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0008_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='full_name',
            field=models.CharField(max_length=60),
        ),
    ]
